#############################################################################
# Makefile for building: duicontrolpanel
# Generated by qmake (2.01a) (Qt 4.5.0) on: Mon Feb 23 18:00:20 2009
# Project:  duicontrolpanel.pro
# Template: app
# Command: /usr/bin/qmake -unix -o Makefile duicontrolpanel.pro
#############################################################################

####### Compiler, tools and options

CC            = @echo compiling $< && gcc
CXX           = @echo compiling $< && g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/targets/i386/usr/share/qt4/mkspecs/linux-g++-opengl -I. -I/targets/i386/usr/include/qt4/QtCore -I/targets/i386/usr/include/qt4/QtGui -I/targets/i386/usr/include/qt4 -I. -Isrc -Isrc/pagefactory -Isrc/base/page -Isrc/page/main -Isrc/page/account -Isrc/page/applet -Isrc/widget -Isrc/base/duisettigscomponent -Isrc/base/maincategory -Isrc/base/simplecategory -Isrc/base/simplecomponent -I/targets/i386/usr/include/qt4/dui -Itmp -I.
LINK          = @echo linking $@ && g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -Wl,-rpath-link=/usr/lib -ldui -lQtGui -lQtCore -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = tmp/

####### Files

SOURCES       = qrc_duicontrolpanel.cpp \
		src/main.cpp \
		src/mainwindow.cpp \
		src/pagefactory/pagefactory.cpp \
		src/widget/button2.cpp \
		src/widget/mostusedcontainer.cpp \
		src/base/duisettigscomponent/duisettingscategory.cpp \
		src/base/duisettigscomponent/duisettingscomponent.cpp \
		src/base/maincategory/duimaincategory.cpp \
		src/base/page/duibackgroundview.cpp \
		src/base/page/duisettingscategorypage.cpp \
		src/base/page/duisettingspage.cpp \
		src/base/simplecategory/duisimplecategory.cpp \
		src/base/simplecomponent/duisimplecomponent.cpp \
		src/page/account/duiaccountcomponent.cpp \
		src/page/account/duisettingsaccountspage.cpp \
		src/page/applet/duisettingsappletpage.cpp \
		src/page/main/duibackgroundcomponent.cpp \
		src/page/main/duidescriptioncomponent.cpp \
		src/page/main/duirecentlyusedcomponent.cpp \
		src/page/main/duisettingsmainpage.cpp tmp/moc_mainwindow.cpp \
		tmp/moc_button2.cpp \
		tmp/moc_mostusedcontainer.cpp \
		tmp/moc_duisettingscategory.cpp \
		tmp/moc_duisettingscomponent.cpp \
		tmp/moc_duimaincategory.cpp \
		tmp/moc_duisettingscategorypage.cpp \
		tmp/moc_duisettingspage.cpp \
		tmp/moc_duisimplecategory.cpp \
		tmp/moc_duisimplecomponent.cpp \
		tmp/moc_duiaccountcomponent.cpp \
		tmp/moc_duisettingsaccountspage.cpp \
		tmp/moc_duisettingsappletpage.cpp \
		tmp/moc_duibackgroundcomponent.cpp \
		tmp/moc_duidescriptioncomponent.cpp \
		tmp/moc_duirecentlyusedcomponent.cpp \
		tmp/moc_duisettingsmainpage.cpp
OBJECTS       = tmp/qrc_duicontrolpanel.o \
		tmp/main.o \
		tmp/mainwindow.o \
		tmp/pagefactory.o \
		tmp/button2.o \
		tmp/mostusedcontainer.o \
		tmp/duisettingscategory.o \
		tmp/duisettingscomponent.o \
		tmp/duimaincategory.o \
		tmp/duibackgroundview.o \
		tmp/duisettingscategorypage.o \
		tmp/duisettingspage.o \
		tmp/duisimplecategory.o \
		tmp/duisimplecomponent.o \
		tmp/duiaccountcomponent.o \
		tmp/duisettingsaccountspage.o \
		tmp/duisettingsappletpage.o \
		tmp/duibackgroundcomponent.o \
		tmp/duidescriptioncomponent.o \
		tmp/duirecentlyusedcomponent.o \
		tmp/duisettingsmainpage.o \
		tmp/moc_mainwindow.o \
		tmp/moc_button2.o \
		tmp/moc_mostusedcontainer.o \
		tmp/moc_duisettingscategory.o \
		tmp/moc_duisettingscomponent.o \
		tmp/moc_duimaincategory.o \
		tmp/moc_duisettingscategorypage.o \
		tmp/moc_duisettingspage.o \
		tmp/moc_duisimplecategory.o \
		tmp/moc_duisimplecomponent.o \
		tmp/moc_duiaccountcomponent.o \
		tmp/moc_duisettingsaccountspage.o \
		tmp/moc_duisettingsappletpage.o \
		tmp/moc_duibackgroundcomponent.o \
		tmp/moc_duidescriptioncomponent.o \
		tmp/moc_duirecentlyusedcomponent.o \
		tmp/moc_duisettingsmainpage.o
DIST          = /targets/i386/usr/share/qt4/mkspecs/common/g++.conf \
		/targets/i386/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/i386/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/i386/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/i386/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/default_pre.prf \
		debian/deb.pri \
		/targets/i386/usr/share/qt4/mkspecs/features/debug.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/silent.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/lex.prf \
		duicontrolpanel.pro
QMAKE_TARGET  = duicontrolpanel
DESTDIR       = 
TARGET        = duicontrolpanel

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: duicontrolpanel.pro  /targets/i386/usr/share/qt4/mkspecs/linux-g++-opengl/qmake.conf /targets/i386/usr/share/qt4/mkspecs/common/g++.conf \
		/targets/i386/usr/share/qt4/mkspecs/common/unix.conf \
		/targets/i386/usr/share/qt4/mkspecs/common/linux.conf \
		/targets/i386/usr/share/qt4/mkspecs/qconfig.pri \
		/targets/i386/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/qt_config.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/default_pre.prf \
		debian/deb.pri \
		/targets/i386/usr/share/qt4/mkspecs/features/debug.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/default_post.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/warn_on.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/silent.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/qt.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/moc.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/resources.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/uic.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/yacc.prf \
		/targets/i386/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -unix -o Makefile duicontrolpanel.pro
/targets/i386/usr/share/qt4/mkspecs/common/g++.conf:
/targets/i386/usr/share/qt4/mkspecs/common/unix.conf:
/targets/i386/usr/share/qt4/mkspecs/common/linux.conf:
/targets/i386/usr/share/qt4/mkspecs/qconfig.pri:
/targets/i386/usr/share/qt4/mkspecs/features/qt_functions.prf:
/targets/i386/usr/share/qt4/mkspecs/features/qt_config.prf:
/targets/i386/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/targets/i386/usr/share/qt4/mkspecs/features/default_pre.prf:
debian/deb.pri:
/targets/i386/usr/share/qt4/mkspecs/features/debug.prf:
/targets/i386/usr/share/qt4/mkspecs/features/default_post.prf:
/targets/i386/usr/share/qt4/mkspecs/features/warn_on.prf:
/targets/i386/usr/share/qt4/mkspecs/features/silent.prf:
/targets/i386/usr/share/qt4/mkspecs/features/qt.prf:
/targets/i386/usr/share/qt4/mkspecs/features/unix/thread.prf:
/targets/i386/usr/share/qt4/mkspecs/features/moc.prf:
/targets/i386/usr/share/qt4/mkspecs/features/resources.prf:
/targets/i386/usr/share/qt4/mkspecs/features/uic.prf:
/targets/i386/usr/share/qt4/mkspecs/features/yacc.prf:
/targets/i386/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile duicontrolpanel.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp/duicontrolpanel1.0.0 || $(MKDIR) tmp/duicontrolpanel1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp/duicontrolpanel1.0.0/ && $(COPY_FILE) --parents src/mainwindow.h src/pagefactory/pagefactory.h src/pagefactory/pages.h src/widget/button2.h src/widget/mostusedcontainer.h src/base/duisettigscomponent/duisettingscategory.h src/base/duisettigscomponent/duisettingscomponent.h src/base/maincategory/duimaincategory.h src/base/page/duibackgroundview.h src/base/page/duisettingscategorypage.h src/base/page/duisettingspage.h src/base/simplecategory/duisimplecategory.h src/base/simplecomponent/duisimplecomponent.h src/page/account/duiaccountcomponent.h src/page/account/duisettingsaccountspage.h src/page/applet/duisettingsappletpage.h src/page/main/duibackgroundcomponent.h src/page/main/duidescriptioncomponent.h src/page/main/duirecentlyusedcomponent.h src/page/main/duisettingsmainpage.h tmp/duicontrolpanel1.0.0/ && $(COPY_FILE) --parents qrc_duicontrolpanel.cpp src/main.cpp src/mainwindow.cpp src/pagefactory/pagefactory.cpp src/widget/button2.cpp src/widget/mostusedcontainer.cpp src/base/duisettigscomponent/duisettingscategory.cpp src/base/duisettigscomponent/duisettingscomponent.cpp src/base/maincategory/duimaincategory.cpp src/base/page/duibackgroundview.cpp src/base/page/duisettingscategorypage.cpp src/base/page/duisettingspage.cpp src/base/simplecategory/duisimplecategory.cpp src/base/simplecomponent/duisimplecomponent.cpp src/page/account/duiaccountcomponent.cpp src/page/account/duisettingsaccountspage.cpp src/page/applet/duisettingsappletpage.cpp src/page/main/duibackgroundcomponent.cpp src/page/main/duidescriptioncomponent.cpp src/page/main/duirecentlyusedcomponent.cpp src/page/main/duisettingsmainpage.cpp tmp/duicontrolpanel1.0.0/ && (cd `dirname tmp/duicontrolpanel1.0.0` && $(TAR) duicontrolpanel1.0.0.tar duicontrolpanel1.0.0 && $(COMPRESS) duicontrolpanel1.0.0.tar) && $(MOVE) `dirname tmp/duicontrolpanel1.0.0`/duicontrolpanel1.0.0.tar.gz . && $(DEL_FILE) -r tmp/duicontrolpanel1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


deb: FORCE
	dpkg-buildpackage -rfakeroot -b

changelog: FORCE
	./debian/updatechangelog

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: tmp/moc_mainwindow.cpp tmp/moc_button2.cpp tmp/moc_mostusedcontainer.cpp tmp/moc_duisettingscategory.cpp tmp/moc_duisettingscomponent.cpp tmp/moc_duimaincategory.cpp tmp/moc_duisettingscategorypage.cpp tmp/moc_duisettingspage.cpp tmp/moc_duisimplecategory.cpp tmp/moc_duisimplecomponent.cpp tmp/moc_duiaccountcomponent.cpp tmp/moc_duisettingsaccountspage.cpp tmp/moc_duisettingsappletpage.cpp tmp/moc_duibackgroundcomponent.cpp tmp/moc_duidescriptioncomponent.cpp tmp/moc_duirecentlyusedcomponent.cpp tmp/moc_duisettingsmainpage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) tmp/moc_mainwindow.cpp tmp/moc_button2.cpp tmp/moc_mostusedcontainer.cpp tmp/moc_duisettingscategory.cpp tmp/moc_duisettingscomponent.cpp tmp/moc_duimaincategory.cpp tmp/moc_duisettingscategorypage.cpp tmp/moc_duisettingspage.cpp tmp/moc_duisimplecategory.cpp tmp/moc_duisimplecomponent.cpp tmp/moc_duiaccountcomponent.cpp tmp/moc_duisettingsaccountspage.cpp tmp/moc_duisettingsappletpage.cpp tmp/moc_duibackgroundcomponent.cpp tmp/moc_duidescriptioncomponent.cpp tmp/moc_duirecentlyusedcomponent.cpp tmp/moc_duisettingsmainpage.cpp
tmp/moc_mainwindow.cpp: src/pagefactory/pages.h \
		src/mainwindow.h
	@echo moc src/mainwindow.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/mainwindow.h -o tmp/moc_mainwindow.cpp

tmp/moc_button2.cpp: src/widget/button2.h
	@echo moc src/widget/button2.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/widget/button2.h -o tmp/moc_button2.cpp

tmp/moc_mostusedcontainer.cpp: src/widget/mostusedcontainer.h
	@echo moc src/widget/mostusedcontainer.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/widget/mostusedcontainer.h -o tmp/moc_mostusedcontainer.cpp

tmp/moc_duisettingscategory.cpp: src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h \
		src/base/duisettigscomponent/duisettingscategory.h
	@echo moc src/base/duisettigscomponent/duisettingscategory.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/base/duisettigscomponent/duisettingscategory.h -o tmp/moc_duisettingscategory.cpp

tmp/moc_duisettingscomponent.cpp: src/pagefactory/pages.h \
		src/base/duisettigscomponent/duisettingscomponent.h
	@echo moc src/base/duisettigscomponent/duisettingscomponent.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/base/duisettigscomponent/duisettingscomponent.h -o tmp/moc_duisettingscomponent.cpp

tmp/moc_duimaincategory.cpp: src/base/duisettigscomponent/duisettingscategory.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h \
		src/base/maincategory/duimaincategory.h
	@echo moc src/base/maincategory/duimaincategory.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/base/maincategory/duimaincategory.h -o tmp/moc_duimaincategory.cpp

tmp/moc_duisettingscategorypage.cpp: src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/base/page/duisettingscategorypage.h
	@echo moc src/base/page/duisettingscategorypage.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/base/page/duisettingscategorypage.h -o tmp/moc_duisettingscategorypage.cpp

tmp/moc_duisettingspage.cpp: src/pagefactory/pages.h \
		src/base/page/duisettingspage.h
	@echo moc src/base/page/duisettingspage.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/base/page/duisettingspage.h -o tmp/moc_duisettingspage.cpp

tmp/moc_duisimplecategory.cpp: src/base/duisettigscomponent/duisettingscategory.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h \
		src/base/simplecategory/duisimplecategory.h
	@echo moc src/base/simplecategory/duisimplecategory.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/base/simplecategory/duisimplecategory.h -o tmp/moc_duisimplecategory.cpp

tmp/moc_duisimplecomponent.cpp: src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h \
		src/base/simplecomponent/duisimplecomponent.h
	@echo moc src/base/simplecomponent/duisimplecomponent.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/base/simplecomponent/duisimplecomponent.h -o tmp/moc_duisimplecomponent.cpp

tmp/moc_duiaccountcomponent.cpp: src/base/simplecomponent/duisimplecomponent.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h \
		src/page/account/duiaccountcomponent.h
	@echo moc src/page/account/duiaccountcomponent.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/page/account/duiaccountcomponent.h -o tmp/moc_duiaccountcomponent.cpp

tmp/moc_duisettingsaccountspage.cpp: src/base/page/duisettingscategorypage.h \
		src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/page/account/duisettingsaccountspage.h
	@echo moc src/page/account/duisettingsaccountspage.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/page/account/duisettingsaccountspage.h -o tmp/moc_duisettingsaccountspage.cpp

tmp/moc_duisettingsappletpage.cpp: src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/page/applet/duisettingsappletpage.h
	@echo moc src/page/applet/duisettingsappletpage.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/page/applet/duisettingsappletpage.h -o tmp/moc_duisettingsappletpage.cpp

tmp/moc_duibackgroundcomponent.cpp: src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h \
		src/page/main/duibackgroundcomponent.h
	@echo moc src/page/main/duibackgroundcomponent.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/page/main/duibackgroundcomponent.h -o tmp/moc_duibackgroundcomponent.cpp

tmp/moc_duidescriptioncomponent.cpp: src/page/main/duibackgroundcomponent.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h \
		src/page/main/duidescriptioncomponent.h
	@echo moc src/page/main/duidescriptioncomponent.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/page/main/duidescriptioncomponent.h -o tmp/moc_duidescriptioncomponent.cpp

tmp/moc_duirecentlyusedcomponent.cpp: src/page/main/duibackgroundcomponent.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h \
		src/page/main/duirecentlyusedcomponent.h
	@echo moc src/page/main/duirecentlyusedcomponent.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/page/main/duirecentlyusedcomponent.h -o tmp/moc_duirecentlyusedcomponent.cpp

tmp/moc_duisettingsmainpage.cpp: src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/page/main/duisettingsmainpage.h
	@echo moc src/page/main/duisettingsmainpage.h && /usr/bin/moc $(DEFINES) $(INCPATH) src/page/main/duisettingsmainpage.h -o tmp/moc_duisettingsmainpage.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

tmp/qrc_duicontrolpanel.o: qrc_duicontrolpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/qrc_duicontrolpanel.o qrc_duicontrolpanel.cpp

tmp/main.o: src/main.cpp src/mainwindow.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/main.o src/main.cpp

tmp/mainwindow.o: src/mainwindow.cpp src/mainwindow.h \
		src/pagefactory/pages.h \
		src/pagefactory/pagefactory.h \
		src/base/page/duisettingspage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/mainwindow.o src/mainwindow.cpp

tmp/pagefactory.o: src/pagefactory/pagefactory.cpp src/pagefactory/pagefactory.h \
		src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/page/main/duisettingsmainpage.h \
		src/page/account/duisettingsaccountspage.h \
		src/base/page/duisettingscategorypage.h \
		src/page/applet/duisettingsappletpage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/pagefactory.o src/pagefactory/pagefactory.cpp

tmp/button2.o: src/widget/button2.cpp src/widget/button2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/button2.o src/widget/button2.cpp

tmp/mostusedcontainer.o: src/widget/mostusedcontainer.cpp src/widget/button2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/mostusedcontainer.o src/widget/mostusedcontainer.cpp

tmp/duisettingscategory.o: src/base/duisettigscomponent/duisettingscategory.cpp src/base/duisettigscomponent/duisettingscategory.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisettingscategory.o src/base/duisettigscomponent/duisettingscategory.cpp

tmp/duisettingscomponent.o: src/base/duisettigscomponent/duisettingscomponent.cpp src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisettingscomponent.o src/base/duisettigscomponent/duisettingscomponent.cpp

tmp/duimaincategory.o: src/base/maincategory/duimaincategory.cpp src/base/maincategory/duimaincategory.h \
		src/base/duisettigscomponent/duisettingscategory.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duimaincategory.o src/base/maincategory/duimaincategory.cpp

tmp/duibackgroundview.o: src/base/page/duibackgroundview.cpp src/base/page/duibackgroundview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duibackgroundview.o src/base/page/duibackgroundview.cpp

tmp/duisettingscategorypage.o: src/base/page/duisettingscategorypage.cpp src/base/page/duisettingscategorypage.h \
		src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/base/maincategory/duimaincategory.h \
		src/base/duisettigscomponent/duisettingscategory.h \
		src/base/duisettigscomponent/duisettingscomponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisettingscategorypage.o src/base/page/duisettingscategorypage.cpp

tmp/duisettingspage.o: src/base/page/duisettingspage.cpp src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/base/page/duibackgroundview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisettingspage.o src/base/page/duisettingspage.cpp

tmp/duisimplecategory.o: src/base/simplecategory/duisimplecategory.cpp src/base/simplecategory/duisimplecategory.h \
		src/base/duisettigscomponent/duisettingscategory.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisimplecategory.o src/base/simplecategory/duisimplecategory.cpp

tmp/duisimplecomponent.o: src/base/simplecomponent/duisimplecomponent.cpp src/base/simplecomponent/duisimplecomponent.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisimplecomponent.o src/base/simplecomponent/duisimplecomponent.cpp

tmp/duiaccountcomponent.o: src/page/account/duiaccountcomponent.cpp src/page/account/duiaccountcomponent.h \
		src/base/simplecomponent/duisimplecomponent.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duiaccountcomponent.o src/page/account/duiaccountcomponent.cpp

tmp/duisettingsaccountspage.o: src/page/account/duisettingsaccountspage.cpp src/page/account/duisettingsaccountspage.h \
		src/base/page/duisettingscategorypage.h \
		src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/base/maincategory/duimaincategory.h \
		src/base/duisettigscomponent/duisettingscategory.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/page/account/duiaccountcomponent.h \
		src/base/simplecomponent/duisimplecomponent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisettingsaccountspage.o src/page/account/duisettingsaccountspage.cpp

tmp/duisettingsappletpage.o: src/page/applet/duisettingsappletpage.cpp src/page/applet/duisettingsappletpage.h \
		src/base/page/duisettingspage.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisettingsappletpage.o src/page/applet/duisettingsappletpage.cpp

tmp/duibackgroundcomponent.o: src/page/main/duibackgroundcomponent.cpp src/page/main/duibackgroundcomponent.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duibackgroundcomponent.o src/page/main/duibackgroundcomponent.cpp

tmp/duidescriptioncomponent.o: src/page/main/duidescriptioncomponent.cpp src/page/main/duidescriptioncomponent.h \
		src/page/main/duibackgroundcomponent.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duidescriptioncomponent.o src/page/main/duidescriptioncomponent.cpp

tmp/duirecentlyusedcomponent.o: src/page/main/duirecentlyusedcomponent.cpp src/page/main/duirecentlyusedcomponent.h \
		src/page/main/duibackgroundcomponent.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/pagefactory/pages.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duirecentlyusedcomponent.o src/page/main/duirecentlyusedcomponent.cpp

tmp/duisettingsmainpage.o: src/page/main/duisettingsmainpage.cpp src/page/main/duisettingsmainpage.h \
		src/base/page/duisettingspage.h \
		src/pagefactory/pages.h \
		src/base/maincategory/duimaincategory.h \
		src/base/duisettigscomponent/duisettingscategory.h \
		src/base/duisettigscomponent/duisettingscomponent.h \
		src/page/main/duidescriptioncomponent.h \
		src/page/main/duibackgroundcomponent.h \
		src/page/main/duirecentlyusedcomponent.h \
		src/widget/button2.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/duisettingsmainpage.o src/page/main/duisettingsmainpage.cpp

tmp/moc_mainwindow.o: tmp/moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_mainwindow.o tmp/moc_mainwindow.cpp

tmp/moc_button2.o: tmp/moc_button2.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_button2.o tmp/moc_button2.cpp

tmp/moc_mostusedcontainer.o: tmp/moc_mostusedcontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_mostusedcontainer.o tmp/moc_mostusedcontainer.cpp

tmp/moc_duisettingscategory.o: tmp/moc_duisettingscategory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisettingscategory.o tmp/moc_duisettingscategory.cpp

tmp/moc_duisettingscomponent.o: tmp/moc_duisettingscomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisettingscomponent.o tmp/moc_duisettingscomponent.cpp

tmp/moc_duimaincategory.o: tmp/moc_duimaincategory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duimaincategory.o tmp/moc_duimaincategory.cpp

tmp/moc_duisettingscategorypage.o: tmp/moc_duisettingscategorypage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisettingscategorypage.o tmp/moc_duisettingscategorypage.cpp

tmp/moc_duisettingspage.o: tmp/moc_duisettingspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisettingspage.o tmp/moc_duisettingspage.cpp

tmp/moc_duisimplecategory.o: tmp/moc_duisimplecategory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisimplecategory.o tmp/moc_duisimplecategory.cpp

tmp/moc_duisimplecomponent.o: tmp/moc_duisimplecomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisimplecomponent.o tmp/moc_duisimplecomponent.cpp

tmp/moc_duiaccountcomponent.o: tmp/moc_duiaccountcomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duiaccountcomponent.o tmp/moc_duiaccountcomponent.cpp

tmp/moc_duisettingsaccountspage.o: tmp/moc_duisettingsaccountspage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisettingsaccountspage.o tmp/moc_duisettingsaccountspage.cpp

tmp/moc_duisettingsappletpage.o: tmp/moc_duisettingsappletpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisettingsappletpage.o tmp/moc_duisettingsappletpage.cpp

tmp/moc_duibackgroundcomponent.o: tmp/moc_duibackgroundcomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duibackgroundcomponent.o tmp/moc_duibackgroundcomponent.cpp

tmp/moc_duidescriptioncomponent.o: tmp/moc_duidescriptioncomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duidescriptioncomponent.o tmp/moc_duidescriptioncomponent.cpp

tmp/moc_duirecentlyusedcomponent.o: tmp/moc_duirecentlyusedcomponent.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duirecentlyusedcomponent.o tmp/moc_duirecentlyusedcomponent.cpp

tmp/moc_duisettingsmainpage.o: tmp/moc_duisettingsmainpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/moc_duisettingsmainpage.o tmp/moc_duisettingsmainpage.cpp

####### Install

install_target: all FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/retsoft/dui/duicontrolpanel/$(DEBIAN_DESTDIR)/usr/bin/ || $(MKDIR) $(INSTALL_ROOT)/home/retsoft/dui/duicontrolpanel/$(DEBIAN_DESTDIR)/usr/bin/ 
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/home/retsoft/dui/duicontrolpanel/$(DEBIAN_DESTDIR)/usr/bin/$(QMAKE_TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/retsoft/dui/duicontrolpanel/$(DEBIAN_DESTDIR)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/retsoft/dui/duicontrolpanel/$(DEBIAN_DESTDIR)/usr/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

