UITESTS_PREFIX = /usr
TEST_INSTALL_LOCATION *= $${UITESTS_PREFIX}/share/dcp-ui-tests
APP_INSTALL_LOCATION *= $${UITESTS_PREFIX}/lib/dcp-ui-tests
LIB_INSTALL_LOCATION *= $${UITESTS_PREFIX}/lib
HEADER_INSTALL_LOCATION *= $${UITESTS_PREFIX}/include
TEST_THEME_ROOT_LOCATION *= $${UITESTS_PREFIX}/share/

