DESTDIR *= /usr
TEST_INSTALL_LOCATION *= $${DESTDIR}/share/dcp-ui-tests
APP_INSTALL_LOCATION *= $${DESTDIR}/lib/dcp-ui-tests
LIB_INSTALL_LOCATION *= $${DESTDIR}/lib
HEADER_INSTALL_LOCATION *= $${DESTDIR}/include
TEST_THEME_ROOT_LOCATION *= $${DESTDIR}/share/

