usr/lib/duicontrolpanel/applets/libdcpskeletonapplet.so
usr/lib/duicontrolpanel/applets/libdcpskelbuttonapplet.so
usr/lib/duicontrolpanel/applets/libdcpskelsliderapplet.so
usr/lib/duicontrolpanel/applets/libdcpmultipageapplet.so
usr/lib/duicontrolpanel/skeleton.desktop
usr/lib/duicontrolpanel/skelslider.desktop
usr/lib/duicontrolpanel/skelbutton.desktop
usr/lib/duicontrolpanel/multipageexample.desktop
usr/lib/duicontrolpanel/declexample.desktop
usr/lib/duicontrolpanel/declexample2.desktop
usr/share/duicontrolpanel/uidescriptions/example1.xml
usr/share/duicontrolpanel/uidescriptions/example2.xml
usr/lib/duicontrolpanel/externalapp.desktop
usr/share/themes/base/meegotouch/libdcpskeletonapplet/style/libdcpskeletonapplet.css
usr/lib/duicontrolpanel/bv_example*.desktop
usr/share/duicontrolpanel/categories/examples/bv_example* usr/share/duicontrolpanel/categories

