#!/bin/bash

CURDIR=`pwd`
TESTAPP="$1"
TESTAPPL=`echo ${TESTAPP} | tr [:upper:] [:lower:]`
APPFOLDER="${CURDIR}/ta_${TESTAPPL}"
TEMPLATES="${CURDIR}/template"

if [ "${TESTAPP}x" == "x" ]; then
  echo "Usage: `basename $0` <DuiClassName>"
  exit
fi

if [ ! -d ${TEMPLATES} ]; then
  echo "No templates available, executing in wrong directory ?"
  exit
fi

if [ -d ${APPFOLDER} ]; then
  echo "${APPFOLDER} already exists, creating only new files"
else 
  mkdir -p ${APPFOLDER}
  echo Creating a new folder ${APPFOLDER}
fi

cd ${TEMPLATES}
for f in `find . -type f -print`; do
    DIRPART=`dirname $f`
    FILEPART=`basename $f`
    NEWFILEPART=`echo ${FILEPART} | sed -e 's/ta_template/'ta_${TESTAPPL}'/'`
    if [ ! -d "${APPFOLDER}/${DIRPART}" ]; then
        mkdir -p "${APPFOLDER}/${DIRPART}"
    fi
    SRC=${DIRPART}/${FILEPART}
    DST=${APPFOLDER}/${DIRPART}/${NEWFILEPART}
    if [ ! -e "${DST}" ]; then
      sed -e 's/ta_template/ta_'${TESTAPPL}'/' -e  's/MkTaClassName/'${TESTAPP}'/' -e 's/mktaclassname/'${TESTAPPL}'/'  < ${SRC} > ${DST}
    fi
done
cd ${CURDIR}
