/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DuiControlPanelIfAdaptor -a duicontrolpanelifadaptor.h:duicontrolpanelifadaptor.cpp ../../../lib/src/service_interface/com.nokia.DuiControlPanelIf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DUICONTROLPANELIFADAPTOR_H_1253200741
#define DUICONTROLPANELIFADAPTOR_H_1253200741

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.DuiControlPanelIf
 */
class DuiControlPanelIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.DuiControlPanelIf")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.DuiControlPanelIf\" >\n"
"    <method name=\"mainPage\" />\n"
"    <method name=\"categoryPage\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"category\" />\n"
"    </method>\n"
"    <method name=\"appletPage\" >\n"
"      <arg direction=\"in\" type=\"s\" name=\"appletName\" />\n"
"      <arg direction=\"out\" type=\"b\" name=\"\" />\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    DuiControlPanelIfAdaptor(QObject *parent);
    virtual ~DuiControlPanelIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    bool appletPage(const QString &appletName);
    void categoryPage(const QString &category);
    void mainPage();
Q_SIGNALS: // SIGNALS
};

#endif
