/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DuiControlPanelIfAdaptor -a duicontrolpanelifadaptor.h:duicontrolpanelifadaptor.cpp ../../../lib/src/service_interface/com.nokia.DuiControlPanelIf.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "duicontrolpanelifadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DuiControlPanelIfAdaptor
 */

DuiControlPanelIfAdaptor::DuiControlPanelIfAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DuiControlPanelIfAdaptor::~DuiControlPanelIfAdaptor()
{
    // destructor
}

bool DuiControlPanelIfAdaptor::appletPage(const QString &appletName)
{
    // handle method call com.nokia.DuiControlPanelIf.appletPage
    bool out0;
    QMetaObject::invokeMethod(parent(), "appletPage", Q_RETURN_ARG(bool, out0), Q_ARG(QString, appletName));
    return out0;
}

void DuiControlPanelIfAdaptor::categoryPage(const QString &category)
{
    // handle method call com.nokia.DuiControlPanelIf.categoryPage
    QMetaObject::invokeMethod(parent(), "categoryPage", Q_ARG(QString, category));
}

void DuiControlPanelIfAdaptor::mainPage()
{
    // handle method call com.nokia.DuiControlPanelIf.mainPage
    QMetaObject::invokeMethod(parent(), "mainPage");
}

